---
title: 'machine learning : Peer Assessment'
output:
  html_document:
    keep_md: yes
  pdf_document: default
---

***

### overview and summary

We will analyze how well subjects perform a particular weight-lifting exercise by analysing data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants.

The data consists of 160 measurements.

To model a predictor, I took into consideration the following :

- The exercise was the biceps curl, so I tried to focus the measurements on both relative position of belt/forearm/arm/dumbbell as well as relative acceleration of same.

- I generated a number of subsets of measurements with caret's featurePlot(), and attempted to select measurements that generated the most separation in the outcome variable ('classe' - a factor variable indicating how well the subject performed the exercise) as possible.

- A random forest training was selected, as it is good for modeling multi-value factor variables and categorization.

- For cross-validation, a 10-fold (with 3 repeats) was chosen.

- Model accuracy obtained : 81%

- Expected out of sample error : 18%


***

### dataset analysis

```{r}
set.seed(1234)
library(caret)
train <- read.csv(file='pml-training.csv',na.strings=c('#DIV/0!', '', 'NA'),stringsAsFactors=FALSE)
train <- train[, -grep("(kurtosis.*)|(skewness.*belt)|(skewness.*arm)|(skewness.*dumbbell)|(min_yaw_forearm)", colnames(train))]
train <- na.omit(train)
train <- train[,c(8:135)]
train[, c(1:127)] <- sapply(train[, c(1:127)], as.numeric)
train$classe = factor(train$classe)

# train now has 128 cols

featurePlot(x=train[,
  c("max_roll_belt",
  "min_roll_belt",
  "amplitude_roll_belt",
  "gyros_belt_y",
  "gyros_belt_z",
  "max_picth_dumbbell",
  "min_pitch_dumbbell",
  "amplitude_pitch_dumbbell",
  "max_roll_forearm",
  "min_roll_forearm",
  "amplitude_roll_forearm"
  )],
  y = train$classe,
  plot="pairs")



train_control <- trainControl(method="repeatedcv", number=10, repeats=3)
rfpml <- train(I(factor(classe))~
  max_roll_belt+
  min_roll_belt+
  amplitude_roll_belt+
  gyros_belt_x+
  gyros_belt_y+
  gyros_belt_z+
  max_picth_dumbbell+
  min_pitch_dumbbell+
  amplitude_pitch_dumbbell+
  max_roll_forearm+
  min_roll_forearm+
  amplitude_roll_forearm,
data=train, trControl=train_control, method="rf")
print(rfpml)
print(rfpml$finalModel)


 ```

